### ISSUE TITLE
Fix view binding bug on Sample app

### ISSUE THREAD

**Issue by Rkareko** [opensrp/p2p#9]
Sample app crashes with the following error

```
2022-03-03 09:01:38.616 7941-7941/org.smartregister.p2p.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.p2p.sample, PID: 7941
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smartregister.p2p.sample/org.smartregister.p2p.MainActivity}: java.lang.NullPointerException: Missing required view with ID: org.smartregister.p2p.sample:id/toolbar
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Missing required view with ID: org.smartregister.p2p.sample:id/toolbar
        at org.smartregister.p2p.databinding.ActivityMainBinding.bind(ActivityMainBinding.java:66)
        at org.smartregister.p2p.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:48)
        at org.smartregister.p2p.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:38)
        at org.smartregister.p2p.MainActivity.onCreate(MainActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by Rkareko** [comment]
This has been fixed on this [PR](https://github.com/opensrp/p2p/pull/7)
